/*
 * AddContact.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import info.User;

import java.sql.Connection;

import dbTool.DbCon;

/**
 *
 * @author  __USER__
 */
public class AddContact extends javax.swing.JInternalFrame {

	
	/** Creates new form AddContact */
	public AddContact() {
		initComponents();
		this.setLocation(150, 30);
	}
    
	/**
	 * 渲染分组信息
	 */
	private void paint(){
		//for(int i = 0; i < )
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel6 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		addContactNameTxt = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		addContactEmailTxt = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		addContactPhoneTxt = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jLabel5 = new javax.swing.JLabel();
		addContactGroupJcb = new javax.swing.JComboBox();
		addContactOkBtn = new javax.swing.JButton();
		addContactCancelBtn = new javax.swing.JButton();
		addContactEmailLabel = new javax.swing.JLabel();
		addContactPhoneLabel = new javax.swing.JLabel();
		addContactNameLabel = new javax.swing.JLabel();

		setClosable(true);
		setForeground(java.awt.Color.pink);
		setIconifiable(true);
		setMaximizable(true);
		setResizable(true);
		setMaximumSize(new java.awt.Dimension(120, 120));
		setMinimumSize(new java.awt.Dimension(120, 120));
		setOpaque(true);
		setPreferredSize(new java.awt.Dimension(540, 450));

		jPanel1.setMaximumSize(new java.awt.Dimension(100, 100));
		jPanel1.setVerifyInputWhenFocusTarget(false);

		jLabel1.setText("\u59d3      \u540d :");

		addContactNameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				addContactNameTxtFocusLost(evt);
			}
		});

		jLabel2.setText("\u90ae    \u7bb1   :");

		addContactEmailTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				addContactEmailTxtFocusLost(evt);
			}
		});

		jLabel3.setText("\u624b\u673a\u53f7\u7801\uff1a");

		addContactPhoneTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				addContactPhoneTxtFocusLost(evt);
			}
		});

		jLabel4.setText("\u5907   \u6ce8 \uff1a");

		jTextArea1.setColumns(20);
		jTextArea1.setLineWrap(true);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jLabel5.setText("\u5206  \u7ec4 \uff1a");

		addContactGroupJcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));
		addContactGroupJcb.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		addContactOkBtn.setText("\u786e   \u5b9a");

		addContactCancelBtn.setText("\u53d6   \u6d88");

		addContactEmailLabel.setText("  ");

		addContactPhoneLabel.setText("  ");

		addContactNameLabel.setText("  ");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				33,
																				33,
																				33)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								jLabel1,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel5,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel4,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel3,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								63,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel2,
																								javax.swing.GroupLayout.Alignment.LEADING))
																		.addGap(
																				12,
																				12,
																				12)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jScrollPane1)
																						.addComponent(
																								addContactPhoneTxt)
																						.addComponent(
																								addContactGroupJcb,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								122,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								addContactEmailTxt)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												addContactNameTxt,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												253,
																												Short.MAX_VALUE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																						.addComponent(
																								addContactPhoneLabel,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								178,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								addContactEmailLabel,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								180,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								addContactNameLabel,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								175,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				206,
																				206,
																				206)
																		.addComponent(
																				addContactOkBtn)
																		.addGap(
																				35,
																				35,
																				35)
																		.addComponent(
																				addContactCancelBtn)))
										.addContainerGap(98, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(addContactNameLabel)
										.addGap(5, 5, 5)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																addContactNameTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																26,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												addContactEmailLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												17,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																addContactEmailTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(addContactPhoneLabel)
										.addGap(6, 6, 6)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																addContactPhoneTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3))
										.addGap(21, 21, 21)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel4)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																58,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																addContactGroupJcb,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																addContactCancelBtn)
														.addComponent(
																addContactOkBtn))
										.addContainerGap(47, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				615,
																				615,
																				615)
																		.addComponent(
																				jLabel6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				150,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				48,
																				48,
																				48)
																		.addComponent(
																				jPanel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel6).addGap(18, 18, 18).addComponent(
								jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								31, 31, 31)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
    /**
     * 验证手机格式是否有误
     */
	private void addContactPhoneTxtFocusLost(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		String str = this.addContactPhoneTxt.getText();
		if (!str
				.matches("/^(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57])[0-9]{8}$/")) {
			this.addContactPhoneLabel.setText("手机格式错误，请重新输入");
		} else {
			this.addContactPhoneLabel.setText(" ");
		}
	}
    
	/**
	 * 验证邮箱格式是否有误
	 * @param evt
	 */
	private void addContactEmailTxtFocusLost(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		String str = this.addContactEmailTxt.getText();
		if (!str
				.matches("[\\w!#$%&'*+/=?^_`{|}~-]+(?:\\.[\\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\\w](?:[\\w-]*[\\w])?\\.)+[\\w](?:[\\w-]*[\\w])?")) {
			this.addContactEmailLabel.setText("邮箱格式错误，请重新输入");
		} else {
			this.addContactEmailLabel.setText(" ");
		}
	}
    
	/**
	 * 验证姓名是否有误
	 * @param evt
	 */
	private void addContactNameTxtFocusLost(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		String str = this.addContactNameTxt.getText();
		if (!str.matches("[\u4E00-\u9FA5]{2,5}(?:·[\u4E00-\u9FA5]{2,5})*")) {
			this.addContactNameLabel.setText("姓名格式错误，请重新输入");
		} else {
			this.addContactNameLabel.setText(" ");
		}
	}

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton addContactCancelBtn;
	private javax.swing.JLabel addContactEmailLabel;
	private javax.swing.JTextField addContactEmailTxt;
	private javax.swing.JLabel addContactNameLabel;
	private javax.swing.JTextField addContactNameTxt;
	private javax.swing.JButton addContactOkBtn;
	private javax.swing.JLabel addContactPhoneLabel;
	private javax.swing.JTextField addContactPhoneTxt;
	private javax.swing.JComboBox addContactGroupJcb;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables

}