/*
 * AddContact.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import util.Check;

import dbTool.GetDataFromDb;
import dbTool.UpdateDb;

import info.Contacts;
import info.User;

/**
 *
 * @author  __USER__
 */
public class AddContact extends javax.swing.JInternalFrame {

	private boolean sign = false;
	private User user; //用户信息

	/** Creates new form AddContact */
	public AddContact() {
		initComponents();
	}

	public AddContact(User user) {
		initComponents();
		this.setLocation(150, 30);
		this.user = user;
		paint(user);
	}

	/**
	 * 渲染复合框中的分组信息
	 */
	private void paint(User user) {
		/**
		 * 哈希表去重,渲染复合框，填入用户所有联系人组
		 */
		this.addContactGroupCb.removeAllItems();
		java.util.Iterator<String> it = user.getAllGroupName().iterator();
		while (it.hasNext()) {
			String str = it.next();
			this.addContactGroupCb.addItem(str);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		addContactNameLabel = new java.awt.Label();
		addContactNameTxt = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		addContactPhoneLabel = new javax.swing.JLabel();
		addContactPhoneTxt = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		addContactEmailLabel = new javax.swing.JLabel();
		addContactEmailTxt = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		addContactGroupCb = new javax.swing.JComboBox();
		addContactOkBtn = new javax.swing.JButton();
		addContactCancel = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		addContactTelephoneTxt = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		addContactAddressTxt = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		addContactWorkplaceTxt = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		addContactBirthdayTxt = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		addContactRemarkTxtField = new javax.swing.JTextArea();

		setClosable(true);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		addContactNameLabel.setBackground(new java.awt.Color(240, 240, 240));
		addContactNameLabel.setText("    ");

		addContactNameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				addContactNameTxtFocusLost(evt);
			}
		});

		jLabel1.setText("   \u6027    \u522b\uff1a");

		jLabel2.setBackground(new java.awt.Color(255, 0, 0));
		jLabel2.setText("   \u59d3    \u540d\uff1a");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"男", "女" }));

		addContactPhoneLabel.setBackground(new java.awt.Color(255, 0, 0));
		addContactPhoneLabel.setText("   ");

		addContactPhoneTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				addContactPhoneTxtFocusLost(evt);
			}
		});

		jLabel4.setText(" \u624b\u673a\u53f7\u7801\uff1a");

		addContactEmailLabel.setText("   ");

		addContactEmailTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				addContactEmailTxtFocusLost(evt);
			}
		});

		jLabel6.setText(" \u8054\u7cfb\u90ae\u7bb1\uff1a");

		jLabel7.setText("   \u5206    \u7ec4\uff1a");

		addContactGroupCb.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "联系人所在分组" }));

		addContactOkBtn.setText("\u786e  \u5b9a");
		addContactOkBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addContactOkBtnActionPerformed(evt);
			}
		});

		addContactCancel.setText("\u8fd4  \u56de");
		addContactCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addContactCancelActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel6,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																66,
																Short.MAX_VALUE)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																66,
																Short.MAX_VALUE))
										.addGap(28, 28, 28)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																addContactEmailTxt,
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																addContactEmailLabel,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																addContactPhoneTxt,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																304,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(94, 94, 94))
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												66, Short.MAX_VALUE)
										.addGap(28, 28, 28)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																addContactNameTxt,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																304,
																Short.MAX_VALUE)
														.addComponent(
																addContactNameLabel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																304,
																Short.MAX_VALUE))
										.addGap(96, 96, 96))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												66, Short.MAX_VALUE)
										.addGap(28, 28, 28)
										.addComponent(
												jComboBox1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												99,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(299, 299, 299))
						.addGroup(
								jPanel2Layout.createSequentialGroup().addGap(
										106, 106, 106).addComponent(
										addContactPhoneLabel,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										304, Short.MAX_VALUE)
										.addGap(94, 94, 94))
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jLabel7,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												66, Short.MAX_VALUE)
										.addGap(28, 28, 28)
										.addComponent(
												addContactGroupCb,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												98,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(300, 300, 300)).addGroup(
								jPanel2Layout.createSequentialGroup().addGap(
										144, 144, 144).addComponent(
										addContactOkBtn).addGap(58, 58, 58)
										.addComponent(addContactCancel)
										.addContainerGap(172, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												addContactNameLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																addContactNameTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2))
										.addGap(20, 20, 20)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												addContactPhoneLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												15,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																addContactPhoneTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(addContactEmailLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																addContactEmailTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												23, Short.MAX_VALUE)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(
																addContactGroupCb,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(23, 23, 23)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																addContactOkBtn)
														.addComponent(
																addContactCancel))
										.addContainerGap()));

		jTabbedPane1.addTab("\u57fa\u672c\u4fe1\u606f", jPanel2);

		jLabel3.setText("\u8054\u7cfb\u7535\u8bdd\uff1a");

		jLabel5.setText("\u8054\u7cfb\u5730\u5740\uff1a");

		jLabel8.setText("\u5de5\u4f5c\u5355\u4f4d\uff1a");

		addContactWorkplaceTxt
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
					//	addContactWorkplaceTxtActionPerformed(evt);
					}
				});

		jLabel9.setText("\u751f      \u65e5\uff1a");

		jLabel10.setText("\u5907      \u6ce8\uff1a");

		addContactRemarkTxtField.setColumns(20);
		addContactRemarkTxtField.setRows(5);
		jScrollPane1.setViewportView(addContactRemarkTxtField);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(26, 26, 26)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addComponent(
																				jLabel9,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel5,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel3,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				74,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel8,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addComponent(jLabel10))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																337,
																Short.MAX_VALUE)
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addComponent(
																				addContactBirthdayTxt)
																		.addComponent(
																				addContactWorkplaceTxt)
																		.addComponent(
																				addContactAddressTxt)
																		.addComponent(
																				addContactTelephoneTxt,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				337,
																				Short.MAX_VALUE)))
										.addContainerGap(62, Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(29, 29, 29)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																addContactTelephoneTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel5)
														.addComponent(
																addContactAddressTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																addContactWorkplaceTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel8))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel9)
														.addComponent(
																addContactBirthdayTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel10)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																135,
																Short.MAX_VALUE))
										.addContainerGap()));

		jTabbedPane1.addTab("\u8865\u5145\u4fe1\u606f", jPanel3);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jTabbedPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 509,
								Short.MAX_VALUE).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jTabbedPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 363,
								Short.MAX_VALUE).addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(
						jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(
						jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 返回按钮，返回主界面并刷新主界面
	 */
	private void addContactCancelActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int n = JOptionPane.showConfirmDialog(null, "是否要返回主界面?");
		if (n == 0) {
			this.dispose();
			user.getMainForm().paintTable();
		}
	}

	/**
	 *确定按钮，点击时，提交联系人信息到数据库
	 * @param evt
	 */
	private void addContactOkBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (sign == true) {

			Contacts contact = new Contacts();
			contact.setName(this.addContactNameTxt.getText());
			contact.setEmail(this.addContactEmailTxt.getText());
			contact.setPhone(this.addContactPhoneTxt.getText());
			String groupName = this.addContactGroupCb.getSelectedItem()
					.toString();
			contact.setGroupName(groupName);
			
			if (this.addContactGroupCb.getSelectedIndex() == 0) {
				contact.setSex("男");
			} else {
				contact.setSex("女");
			}
			contact.setRemark(this.addContactRemarkTxtField.getText());
			contact.setBirthday(this.addContactBirthdayTxt.getText());
			contact.setTelephone(this.addContactTelephoneTxt.getText());
			contact.setWorkplace(this.addContactWorkplaceTxt.getText());
			try {
				int gid = GetDataFromDb.getGid(contact, user);
				contact.setGid(gid);
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			try {
				boolean flag = UpdateDb.addContactToDb(user, contact);
				if (flag) {
					JOptionPane.showConfirmDialog(null, "联系人添加成功");
					this.addContactNameTxt.setText("");
					this.addContactEmailTxt.setText("");
					this.addContactPhoneTxt.setText("");
					this.addContactRemarkTxtField.setText("");
					this.addContactTelephoneTxt.setText("");
					this.addContactAddressTxt.setText("");
					this.addContactWorkplaceTxt.setText("");
					user.getMainForm().paintTable();
				} else {
					JOptionPane.showConfirmDialog(null, "联系人添加失败，请检查填写信息");
				}
			} catch (Exception ex) {

			}
		}
	}

	/**
	 * 联系邮箱格式验证
	 */
	private void addContactEmailTxtFocusLost(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		String str = this.addContactEmailTxt.getText();
		if (!Check.isEmail(str)) {
			this.addContactEmailLabel.setText("邮箱格式错误，请重新输入");
			sign = false;
		} else {
			this.addContactEmailLabel.setText("  ");
		}
	}

	/**
	 * 手机号码格式验证
	 * @param evt
	 */
	private void addContactPhoneTxtFocusLost(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		String str = this.addContactPhoneTxt.getText();
		if (!Check.isPhone(str)) {
			this.addContactPhoneLabel.setText("手机格式错误，请重新输入");
			sign = false;
		} else {
			this.addContactPhoneLabel.setText(" ");
			sign = true;
		}
	}

	/**
	 * 人名格式验证
	 * @param evt
	 */
	private void addContactNameTxtFocusLost(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		String str = this.addContactNameTxt.getText();
		if (!Check.isName(str)) {
			this.addContactNameLabel.setText("姓名格式错误，请重新输入");
			sign = false;
		} else {
			this.addContactNameLabel.setText(" ");
			sign = true;
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField addContactAddressTxt;
	private javax.swing.JTextField addContactBirthdayTxt;
	private javax.swing.JButton addContactCancel;
	private javax.swing.JLabel addContactEmailLabel;
	private javax.swing.JTextField addContactEmailTxt;
	private javax.swing.JComboBox addContactGroupCb;
	private java.awt.Label addContactNameLabel;
	private javax.swing.JTextField addContactNameTxt;
	private javax.swing.JButton addContactOkBtn;
	private javax.swing.JLabel addContactPhoneLabel;
	private javax.swing.JTextField addContactPhoneTxt;
	private javax.swing.JTextArea addContactRemarkTxtField;
	private javax.swing.JTextField addContactTelephoneTxt;
	private javax.swing.JTextField addContactWorkplaceTxt;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTabbedPane jTabbedPane1;
	// End of variables declaration//GEN-END:variables

}