/*
 * AddContact.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import info.Contacts;
import info.User;

import java.security.acl.Group;
import java.sql.Connection;
import java.util.HashSet;

import javax.swing.JOptionPane;
import javax.swing.text.html.HTMLDocument.Iterator;

import dbTool.DbCon;
import dbTool.UpdateDb;

/**
 *
 * @author  __USER__
 */
public class AddContact extends javax.swing.JInternalFrame {

	private boolean sign = false; //用户校验联系人信息是否填写正确
	private User user; //用户信息

	/** Creates new form AddContact */
	public AddContact() {
		initComponents();
		this.setLocation(150, 30);
		this.resizable = true;
	}

	public AddContact(User user) {
		initComponents();
		this.setLocation(150, 30);
		this.user = user;
		paint(user);
	}

	/**
	 * 渲染复合框中的分组信息
	 */
	private void paint(User user) {
		/**
		 * 哈希表去重,渲染复合框，填入用户所有联系人组
		 */
		java.util.Iterator<String> it = user.getAllGroupName().iterator();
		while (it.hasNext()) {
			String str = it.next();
			this.addContactGroupJcb.addItem(str);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel6 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		addContactNameTxt = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		addContactEmailTxt = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		addContactPhoneTxt = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		addContactRemarkTxtField = new javax.swing.JTextArea();
		jLabel5 = new javax.swing.JLabel();
		addContactGroupJcb = new javax.swing.JComboBox();
		addContactOkBtn = new javax.swing.JButton();
		addContactCancelBtn = new javax.swing.JButton();
		addContactEmailLabel = new javax.swing.JLabel();
		addContactPhoneLabel = new javax.swing.JLabel();
		addContactNameLabel = new javax.swing.JLabel();

		setClosable(true);
		setForeground(java.awt.Color.pink);
		setIconifiable(true);
		setMaximizable(true);
		setMaximumSize(new java.awt.Dimension(500, 450));
		setMinimumSize(new java.awt.Dimension(500, 450));
		setOpaque(true);
		setPreferredSize(new java.awt.Dimension(500, 450));

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel1.setMaximumSize(new java.awt.Dimension(500, 500));
		jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
		jPanel1.setVerifyInputWhenFocusTarget(false);

		jLabel1.setText("\u59d3      \u540d :");

		addContactNameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				addContactNameTxtFocusLost(evt);
			}
		});

		jLabel2.setText("\u90ae    \u7bb1   :");

		addContactEmailTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				addContactEmailTxtFocusLost(evt);
			}
		});

		jLabel3.setText("\u624b\u673a\u53f7\u7801\uff1a");

		addContactPhoneTxt.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				addContactPhoneTxtFocusLost(evt);
			}
		});

		jLabel4.setText("\u5907   \u6ce8 \uff1a");

		addContactRemarkTxtField.setColumns(20);
		addContactRemarkTxtField.setLineWrap(true);
		addContactRemarkTxtField.setRows(5);
		jScrollPane1.setViewportView(addContactRemarkTxtField);

		jLabel5.setText("\u5206  \u7ec4 \uff1a");

		addContactOkBtn.setText("\u786e   \u5b9a");
		addContactOkBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addContactOkBtnActionPerformed(evt);
			}
		});

		addContactCancelBtn.setText("\u8fd4  \u56de");
		addContactCancelBtn
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						addContactCancelBtnActionPerformed(evt);
					}
				});

		addContactEmailLabel.setText("  ");

		addContactPhoneLabel.setText("  ");

		addContactNameLabel.setText("  ");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				33,
																				33,
																				33)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								jLabel1,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel5,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel4,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel3,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel2,
																								javax.swing.GroupLayout.Alignment.LEADING))
																		.addGap(
																				12,
																				12,
																				12)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jScrollPane1)
																						.addComponent(
																								addContactPhoneTxt)
																						.addComponent(
																								addContactGroupJcb,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								122,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								addContactEmailTxt)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												addContactNameTxt)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																						.addComponent(
																								addContactPhoneLabel,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								178,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								addContactEmailLabel,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								180,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								addContactNameLabel,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								175,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				205,
																				205,
																				205)
																		.addComponent(
																				addContactOkBtn)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				addContactCancelBtn)))
										.addContainerGap(30, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(addContactNameLabel)
										.addGap(5, 5, 5)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																addContactNameTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																26,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												addContactEmailLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												17,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																addContactEmailTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(addContactPhoneLabel)
										.addGap(6, 6, 6)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																addContactPhoneTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3))
										.addGap(21, 21, 21)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel4)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																58,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																addContactGroupJcb,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(32, 32, 32)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																addContactOkBtn)
														.addComponent(
																addContactCancelBtn))
										.addGap(7, 7, 7)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jLabel6)
						.addContainerGap(480, Short.MAX_VALUE)).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(52,
						Short.MAX_VALUE).addComponent(jPanel1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 391,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(37, 37,
						37)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																376,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 点击返回按钮时，返回主界面
	 */
	private void addContactCancelBtnActionPerformed(
			java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int n = JOptionPane.showConfirmDialog(null, "是否要返回主界面?");
		if (n == 0) {
			this.dispose();
			user.getMainForm().paintTable();
		}

	}

	/**
	 * 单击确定按钮后，将联系人信息提交到数据库
	 */
	private void addContactOkBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (sign == true) {

			Contacts contact = new Contacts();
			contact.setName(this.addContactNameTxt.getText());
			contact.setEmail(this.addContactEmailTxt.getText());
			long phone = Long.parseLong(this.addContactPhoneTxt.getText());
			contact.setPhone(phone);
			String groupName = this.addContactGroupJcb.getSelectedItem()
					.toString();
			contact.setGroupName(groupName);
			contact.setRemark(this.addContactRemarkTxtField.getText());

			try {
				boolean flag = UpdateDb.addContactToDb(user, contact);
				if (flag) {
					JOptionPane.showConfirmDialog(null, "联系人添加成功");
					this.addContactNameTxt.setText("");
					this.addContactEmailTxt.setText("");
					this.addContactPhoneTxt.setText("");
					this.addContactRemarkTxtField.setText("");
				} else {
					JOptionPane.showConfirmDialog(null, "联系人添加失败，请检查填写信息");
				}
			} catch (Exception ex) {

			}

		}
	}

	/**
	 * 验证手机格式是否有误
	 */
	private void addContactPhoneTxtFocusLost(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		String str = this.addContactPhoneTxt.getText();
		if (!str
				.matches("^(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57])[0-9]{8}$")) {
			this.addContactPhoneLabel.setText("手机格式错误，请重新输入");
			sign = false;
		} else {
			this.addContactPhoneLabel.setText(" ");
			sign = true;
		}
	}

	/**
	 * 验证邮箱格式是否有误
	 * @param evt
	 */
	private void addContactEmailTxtFocusLost(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		String str = this.addContactEmailTxt.getText();
		if (!str
				.matches("[\\w!#$%&'*+/=?^_`{|}~-]+(?:\\.[\\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\\w](?:[\\w-]*[\\w])?\\.)+[\\w](?:[\\w-]*[\\w])?")) {
			this.addContactEmailLabel.setText("邮箱格式错误，请重新输入");
			sign = false;
		} else {
			this.addContactEmailLabel.setText(" ");
			sign = true;
		}
	}

	/**
	 * 验证姓名是否有误
	 * @param evt
	 */
	private void addContactNameTxtFocusLost(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		String str = this.addContactNameTxt.getText();
		if (!str.matches("[\u4E00-\u9FA5]{2,5}(?:·[\u4E00-\u9FA5]{2,5})*")) {
			this.addContactNameLabel.setText("姓名格式错误，请重新输入");
			sign = false;
		} else {
			this.addContactNameLabel.setText(" ");
			sign = true;
		}
	}

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton addContactCancelBtn;
	private javax.swing.JLabel addContactEmailLabel;
	private javax.swing.JTextField addContactEmailTxt;
	private javax.swing.JComboBox addContactGroupJcb;
	private javax.swing.JLabel addContactNameLabel;
	private javax.swing.JTextField addContactNameTxt;
	private javax.swing.JButton addContactOkBtn;
	private javax.swing.JLabel addContactPhoneLabel;
	private javax.swing.JTextField addContactPhoneTxt;
	private javax.swing.JTextArea addContactRemarkTxtField;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}