/*
 * AddGroup.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Image;
import java.sql.SQLException;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


import util.Check;
import util.Tool;

import dbTool.GetDataFromDb;
import dbTool.UpdateDb;
import info.User;

/**
 *
 * @author  __USER__
 */
public class AddGroup extends javax.swing.JInternalFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private User user;

	/** Creates new form AddGroup */
	public AddGroup() {
		initComponents();
	}

	public AddGroup(User user) {
		this.user = user;
		initComponents();
		Image img = new ImageIcon("image/R1.png").getImage();
		Icon icon = Tool.createIcon(img, 15, 15);// 读取图标
		this.setFrameIcon(icon); // 设置图标
		this.setLocation(220, 150);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		AddGroupNameTxt = new javax.swing.JTextField();
		AddGroupOkBtn = new javax.swing.JButton();
		AddGroupCancelBtn = new javax.swing.JButton();

		setTitle("\u65b0\u5efa\u8054\u7cfb\u7ec4");

		jLabel1.setText("\u8f93\u5165\u8054\u7cfb\u7ec4\u540d\u79f0\uff1a");

		AddGroupOkBtn.setText("\u786e   \u5b9a");
		AddGroupOkBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AddGroupOkBtnActionPerformed(evt);
			}
		});

		AddGroupCancelBtn.setText("\u8fd4   \u56de");
		AddGroupCancelBtn
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						AddGroupCancelBtnActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				30,
																				30,
																				30)
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				107,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				AddGroupNameTxt,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				215,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				109,
																				109,
																				109)
																		.addComponent(
																				AddGroupOkBtn)
																		.addGap(
																				39,
																				39,
																				39)
																		.addComponent(
																				AddGroupCancelBtn)))
										.addContainerGap(26, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(36, 36, 36)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																AddGroupNameTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																28,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(33, 33, 33)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																AddGroupOkBtn)
														.addComponent(
																AddGroupCancelBtn))
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void AddGroupCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void AddGroupOkBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String groupName = this.AddGroupNameTxt.getText();
		String str = groupName.trim();
		if(!Check.isEmpty(str)){
			try {
				boolean flag = GetDataFromDb.existGroupName(this.user, groupName);
				if (flag) {
					JOptionPane.showMessageDialog(null, "该组名已经存在，请重新输入!");
					return;
				}
				int n = UpdateDb.insertNewGroup(user, groupName);
				if (n == 0) {
					JOptionPane.showMessageDialog(null, "新联系人组添加失败");
				} else {
					JOptionPane.showMessageDialog(null, "新联系人组添加成功");
					this.AddGroupNameTxt.setText("");
					this.user.getMainForm().paintJTree();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else {
			JOptionPane.showMessageDialog(null, "组名有误，请重新输出!");
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton AddGroupCancelBtn;
	private javax.swing.JTextField AddGroupNameTxt;
	private javax.swing.JButton AddGroupOkBtn;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}