/*
 * Login.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import info.User;

import java.awt.Image;
import java.sql.Connection;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

import org.jvnet.lafwidget.combo.ComboboxAutoCompletionWidget;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.border.StandardBorderPainter;
import org.jvnet.substance.button.ClassicButtonShaper;
import org.jvnet.substance.painter.StandardGradientPainter;
import org.jvnet.substance.skin.BusinessSkin;
import org.jvnet.substance.theme.SubstanceCremeTheme;
import org.jvnet.substance.title.FlatTitlePainter;
import org.jvnet.substance.watermark.SubstanceBinaryWatermark;

import util.ProgressBar;
//import util.ProgressBar;

import dbTool.DbCon;
import dbTool.LoginCon;

/**
 *
 * @author  __USER__
 */
public class Login_ extends javax.swing.JFrame {
    
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private static JFrame mainForn;
	private static MainForm mainForm;
	/** Creates new form Login */
	public Login_() {
		initComponents();
		//ImageCodePanel Icp = new ImageCodePanel();
		this.setLocationRelativeTo(null);
		Image img = new ImageIcon("image/R1.png").getImage();
		this.setIconImage(img);
		this.setTitle("通讯录管理系统");
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		loginOkBtn = new javax.swing.JButton();
		loginRegisterBtn = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		loginUserTxt = new javax.swing.JTextField();
		loginPswTxt = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		loginOkBtn.setText("\u767b   \u5f55");
		loginOkBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loginOkBtnActionPerformed(evt);
			}
		});

		loginRegisterBtn.setText("\u6ce8   \u518c");
		loginRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loginRegisterBtnActionPerformed(evt);
			}
		});

		jLabel1.setText("\u7528  \u6237  \u540d \uff1a");

		jLabel2.setText("\u5bc6       \u7801 \uff1a");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(
										119, Short.MAX_VALUE).addComponent(
										loginOkBtn).addGap(70, 70, 70)
										.addComponent(loginRegisterBtn).addGap(
												142, 142, 142))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(84, 84, 84)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																68,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																loginPswTxt)
														.addComponent(
																loginUserTxt,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																218,
																Short.MAX_VALUE))
										.addContainerGap(94, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(90, 90, 90)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																28,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																loginUserTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(38, 38, 38)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																loginPswTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(64, 64, 64)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																loginRegisterBtn)
														.addComponent(
																loginOkBtn))
										.addGap(49, 49, 49)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void loginRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
		Register_ register = new Register_();
		register.setVisible(true);
	}

	private void loginOkBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String username = this.loginUserTxt.getText();
		String password = String.valueOf(loginPswTxt.getPassword());
		Connection con = null;
		User user = null;
		try {
			con = DbCon.getCon();
			user = LoginCon.loginCheck(con, username, password);
			if (user != null) {
				JOptionPane.showMessageDialog(null, "用户登录成功");
				this.dispose();
				mainForm.setUser(user);
				user.setMainForm(mainForm);
/*				MainForm mainForm = new MainForm(user);
				user.setMainForm(mainForm);*/
				mainForm.paintP();
				mainForm.setVisible(true);			
				
			} else {
				JOptionPane.showMessageDialog(null, "用户登录失败");
			}
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		} finally {
			//DbCon.closeCon(con);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
	   	
		mainForn = new Login_();
		//new ProgressBar(mainForn);
		mainForm = new MainForm();
		
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run(){
				try {  
		            UIManager.setLookAndFeel(new SubstanceLookAndFeel());  
		            JFrame.setDefaultLookAndFeelDecorated(true);  
		            JDialog.setDefaultLookAndFeelDecorated(true);  
		            SubstanceLookAndFeel.setCurrentTheme(new SubstanceCremeTheme()); 
		            SubstanceLookAndFeel.setSkin(new BusinessSkin());  
		            SubstanceLookAndFeel.setCurrentButtonShaper(new ClassicButtonShaper());  
		            SubstanceLookAndFeel.setCurrentWatermark(new SubstanceBinaryWatermark());  
		            SubstanceLookAndFeel.setCurrentBorderPainter(new StandardBorderPainter());  
		            SubstanceLookAndFeel.setCurrentGradientPainter(new StandardGradientPainter());  
		            SubstanceLookAndFeel.setCurrentTitlePainter(new FlatTitlePainter());  
		            //SubstanceLookAndFeel.setCurrentCombobox(new ComboboxAutoCompletionWidget());
		            mainForn.setVisible(true);
	
		        } catch (Exception e) {  
		           // System.err.println("Something went wrong!");  
		            JOptionPane.showConfirmDialog(null, "Something went wrong!");
		        }  
				
				
			}
		});

		
		
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JButton loginOkBtn;
	private javax.swing.JPasswordField loginPswTxt;
	private javax.swing.JButton loginRegisterBtn;
	private javax.swing.JTextField loginUserTxt;
	// End of variables declaration//GEN-END:variables

}