/*
 * Login.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import info.User;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.sql.Connection;

import javax.swing.JOptionPane;

import util.ImageCodePanel;

import dbTool.DbCon;
import dbTool.LoginCon;

/**
 *
 * @author  __USER__
 */
public class Login extends javax.swing.JFrame {

	/** Creates new form Login */
	public Login() {
		initComponents();
		ImageCodePanel Icp = new ImageCodePanel();
		Icp.setVisible(true);
		BufferedImage buffImage = new BufferedImage(50, 50, BufferedImage.TYPE_INT_RGB);
		Graphics g = buffImage.getGraphics();
		Icp.paint(g);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		loginUserTxt = new javax.swing.JTextField();
		LoginOkBtn = new javax.swing.JButton();
		loginRegisterBtn = new javax.swing.JButton();
		loginPswTxt = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u7528\u6237\u767b\u5f55");

		jLabel1.setText("\u7528\u6237\u540d\uff1a");

		jLabel2.setText("\u5bc6  \u7801\uff1a");

		LoginOkBtn.setText("\u767b\u5f55");
		LoginOkBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				LoginOkBtnActionPerformed(evt);
			}
		});

		loginRegisterBtn.setText("\u6ce8\u518c");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(79, 79, 79)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																LoginOkBtn,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								jLabel2,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel1,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								63,
																								Short.MAX_VALUE))
																		.addGap(
																				5,
																				5,
																				5)))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				81,
																				81,
																				81)
																		.addComponent(
																				loginRegisterBtn))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								loginPswTxt)
																						.addComponent(
																								loginUserTxt,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								191,
																								Short.MAX_VALUE))))
										.addContainerGap(139, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(112, 112, 112)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																loginUserTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																26,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(51, 51, 51)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																loginPswTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												61, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																loginRegisterBtn)
														.addComponent(
																LoginOkBtn))
										.addGap(60, 60, 60)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void LoginOkBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String username = this.loginUserTxt.getText();
		String password = String.valueOf(loginPswTxt.getPassword());
		Connection con = null;
		User user = null;
		try{
			con = DbCon.getCon();
			user = LoginCon.loginCheck(con, username, password);
			if(user != null) {
				JOptionPane.showConfirmDialog(null, "用户登录成功");
			} else {
				JOptionPane.showConfirmDialog(null, "用户登录失败");
			}
		}catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		} finally{
			DbCon.closeCon(con);
		}
		
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton LoginOkBtn;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPasswordField loginPswTxt;
	private javax.swing.JButton loginRegisterBtn;
	private javax.swing.JTextField loginUserTxt;
	// End of variables declaration//GEN-END:variables

}