/*
 * QueryInfo.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Image;
import java.sql.SQLException;
import java.util.Collections;
import java.util.Vector;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


import util.PinyinComparator;
import util.Tool;

import dbTool.GetDataFromDb;

import info.Contacts;
import info.User;

/**
 *
 * @author  __USER__
 */
public class QueryInfo extends javax.swing.JInternalFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form QueryInfo */
	private User user;

	public QueryInfo() {
		initComponents();
	}

	public QueryInfo(User user) {
		initComponents();
		this.user = user;
		Image img = new ImageIcon("image/R1.png").getImage();
		Icon icon = Tool.createIcon(img, 15, 15);// 读取图标
		this.setFrameIcon(icon); // 设置图标
		this.setLocation(220, 150);
		paint();
	}

	
	 public void paint(){
			this.QueryInfoGroupCb.removeAllItems();
			java.util.Iterator<String> it = user.getAllGroupName().iterator();
			this.QueryInfoGroupCb.addItem(new String("请选择..."));
			while (it.hasNext()) {
				String str = it.next();
				this.QueryInfoGroupCb.addItem(str);
			}
			this.QueryInfoSexCb.removeAllItems();
			this.QueryInfoSexCb.addItem(new String("请选择..."));
			this.QueryInfoSexCb.addItem(new String("男"));
			this.QueryInfoSexCb.addItem(new String("女"));
	 }
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		QueryInfoNameTxt = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		QueryInfoSexCb = new javax.swing.JComboBox();
		jLabel3 = new javax.swing.JLabel();
		QueryInfoPhoneTxt = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		QueryInfoTelephoneTxt = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		QueryInfoGroupCb = new javax.swing.JComboBox();
		QueryInfoQueryBtn = new javax.swing.JButton();
		QueryInfoCancelBtn = new javax.swing.JButton();

		setClosable(true);
		setIconifiable(true);
		setResizable(true);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u641c\u7d22\u6761\u4ef6"));
		jPanel1.setName("");
		jPanel1.setOpaque(false);

		jLabel1.setText("\u59d3  \u540d \uff1a");

		jLabel2.setText("\u6027  \u522b\uff1a");

		QueryInfoSexCb.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "男", "女" }));

		jLabel3.setText("\u624b\u673a\u53f7\u7801\uff1a");

		jLabel4.setText("\u7535\u8bdd\u53f7\u7801\uff1a");

		jLabel5.setText("\u6240\u5728\u5206\u7ec4\uff1a");

		QueryInfoGroupCb.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "好友" }));

		QueryInfoQueryBtn.setText("\u67e5  \u8be2");
		QueryInfoQueryBtn
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						QueryInfoQueryBtnActionPerformed(evt);
					}
				});

		QueryInfoCancelBtn.setText("\u8fd4  \u56de");
		QueryInfoCancelBtn
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						QueryInfoCancelBtnActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jLabel5,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																55,
																Short.MAX_VALUE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				QueryInfoNameTxt,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				131,
																				Short.MAX_VALUE)
																		.addGap(
																				37,
																				37,
																				37))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								QueryInfoQueryBtn)
																						.addComponent(
																								QueryInfoGroupCb,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								111,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				57,
																				57,
																				57))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				QueryInfoPhoneTxt,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				153,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel2))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								QueryInfoSexCb,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								92,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								QueryInfoTelephoneTxt,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								160,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addComponent(
																QueryInfoCancelBtn))
										.addGap(24, 24, 24)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																QueryInfoNameTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2)
														.addComponent(
																QueryInfoSexCb,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jLabel4)
														.addComponent(
																QueryInfoTelephoneTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																QueryInfoPhoneTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																QueryInfoGroupCb,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(46, 46, 46)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																QueryInfoQueryBtn)
														.addComponent(
																QueryInfoCancelBtn))
										.addContainerGap(28, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap(
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void QueryInfoCancelBtnActionPerformed(
			java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int n = JOptionPane.showConfirmDialog(null, "是否返回主界面？");
		if(n == 0){
			this.dispose();
		}
	}

	/**
	 * 查询界面信息与数据库对接，并查询
	 */
	private void QueryInfoQueryBtnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Contacts contact = new Contacts();
		String name = this.QueryInfoNameTxt.getText();
		contact.setName(name);
		String sex = null;
		int n = this.QueryInfoSexCb.getSelectedIndex();
		if (n == 0) {
			sex = "";
		} else if(n == 1){
			sex = "男";
		} else {
			sex = "女";
		}
		contact.setSex(sex);
		String phone = this.QueryInfoPhoneTxt.getText();
		contact.setPhone(phone);
		String telephone = this.QueryInfoTelephoneTxt.getText();
		contact.setTelephone(telephone);
		int m = this.QueryInfoGroupCb.getSelectedIndex();
		String groupName = null;
		if( m == 0 ) {
			groupName = "";
		} else {
			groupName = (String) this.QueryInfoGroupCb.getSelectedItem();
		}
		contact.setGroupName(groupName);
		Vector<Contacts> contactsList = new Vector<Contacts>();
		try {
			contactsList = GetDataFromDb.getInfoFromdb(contact, user);
			Collections.sort(contactsList, new PinyinComparator());
			this.user.setContactsGrounp(contactsList);
			this.user.getMainForm().paintQueryTable();

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton QueryInfoCancelBtn;
	private javax.swing.JComboBox QueryInfoGroupCb;
	private javax.swing.JTextField QueryInfoNameTxt;
	private javax.swing.JTextField QueryInfoPhoneTxt;
	private javax.swing.JButton QueryInfoQueryBtn;
	private javax.swing.JComboBox QueryInfoSexCb;
	private javax.swing.JTextField QueryInfoTelephoneTxt;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}